workflows:
  default-workflow:
    name: Flutter workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          flutter pub upgrade
      - name: Analyze project
        script: |
          flutter analyze
      - name: Run tests
        script: |
          flutter test
    artifacts:
      - build/**

# Add any additional configurations needed
